---
# change as needed or preffered
_gaia_validator_system_group: "gaia"
_gaia_validator_system_user: "{{ _gaia_validator_system_group }}"

GAIA_HOME: "/home/gaia"
gaiad_version: "v5.0.2"
gaiad_binary_location: "/usr/local/bin/gaiad"

# checksums 
gaiad_v4.2.0_sha256: "5687a0ff28141552b82bc25f4c785bafb4932139012c55451937be9b4564f5ae"
gaiad_v5.0.2_sha256: "b528aff8b9e76c91b76b1288cdc15d13fed6b868d8ff3b74460ea2061bacea9b"
genesis_sha1: "116e4bc367e758d14cba9283414961d89a3ba163"

# [config]
admin_password: "rockyou2021"
moniker: "gyrusdentatus"

min_gas_prices: "0.025uatom"
p2p_seeds: "bf8328b66dceb4987e5cd94430af66045e59899f@public-seed.cosmos.vitwit.com:26656,cfd785a4224c7940e9a10f6c1ab24c343e923bec@164.68.107.188:26656,d72b3011ed46d783e369fdf8ae2055b99a1e5074@173.249.50.25:26656,ba3bacc714817218562f743178228f23678b2873@public-seed-node.cosmoshub.certus.one:26656,3c7cad4154967a294b3ba1cc752e40e8779640ad@84.201.128.115:26656"
# [logging]
gaia_log_path: "/usr/local/lib/"